"""empty message

Revision ID: 78e52b3e9867
Revises: 9f468c479e21
Create Date: 2022-08-25 15:01:14.070902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e52b3e9867'
down_revision = '9f468c479e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'category_id')
    # ### end Alembic commands ###
