"""empty message

Revision ID: e2106641b52c
Revises: 78e52b3e9867
Create Date: 2022-08-26 04:09:39.104334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2106641b52c'
down_revision = '78e52b3e9867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_category_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_category_id_fkey', 'users', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
